apiVersion: v1
kind: Service
metadata:
  name: jar
  labels:
    app: jar
spec:
  type: NodePort
  selector:
    app: jar
  ports:
    - port: 8088        # Service port
      targetPort: 8080  # Container port (Tomcat)
      protocol: TCP
